version: "3"

services:

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
    logging:
      driver: none

  mongo-seed:
    build: ./mongo-seed
    command: mongoimport --host mongodb --db buslightyear --collection bus_ping --type csv --headerline --file data.csv
    networks:
      - app-network
    depends_on:
      - mongodb
 
  rabbit:
    image: rabbitmq:3-management
    networks:
      - app-network
 
  producer:
    build: ./producer
    command: npm start
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - ./producer:/app
    depends_on:
      - rabbit

  consumer:
    build: ./consumer
    command: npm start
    ports:
      - "3005:3005"
    networks:
      - app-network
    volumes:
      - ./consumer:/app
    depends_on:
      - rabbit
      - producer

  frontend:
    build: ./frontend
    command: npm start
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./frontend:/app
    depends_on:
      - consumer

networks:
  app-network:
    driver: bridge
